version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile # Dockerfileのディレクトリを指定します
    volumes:
      - '.:/app'
    ports:
      - "8000:8000" # 左側が外部からのアクセス時のポート番号:右側がdockerコンテナからアクセスする時のポート番号。ホストの8000番からコンテナの8000番へポートフォワードしています
    container_name: eyenect
    # tty: true　 # ポート待受とかしていないコンテナの場合、trueに設定しておくとコンテナが起動し続けます
    command: tail -f /dev/null # コンテナが起動し続けるようにするためのコマンドです
    working_dir: '/app'
