databases:
  - name: db.sqlite3
    region: singapore
    plan: free
    databaseName: db.sqlite3
    user: django_user

services:
  - type: web
    name: django_render
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn crops.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db.sqlite3
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true